### ISSUE TITLE
Add a option in nextcloud parameter for activate or desactivate background-color or tada animation

### ISSUE THREAD

**Issue by Ludovicis** [jancborchardt/lsd#6]
Same idea than the unsplash app...
Can you add a option in nextcloud parameter for choose activate or desactivate background-color or tada animation, please ?
example: see the following picture
![lsd](https://user-images.githubusercontent.com/16205280/37466131-4a3714f0-285d-11e8-8796-bc4535fdf120.png)

Thanks,

**Comment by jancborchardt** [comment]
This app is mostly a joke. Either you take LSD or you don’t. ;)

So in keeping with Nextcloud simplicity, let’s not introduce so many settings.
